accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

crewing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web_hiring.urls', namespace="web_hiring")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('vbbot/', include('vbbot.urls', namespace='vbbot'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vbbot/urls.py
from django.urls import path
from django.conf import settings
from vbbot import views

app_name = 'vbbot'
token = settings.VIBER_TOKEN

urlpatterns = [
    path(token, views.viber_app),
    ]

web_hiring/urls.py
from django.urls import path, include
from web_hiring import views

app_name = 'web_hiring'

urlpatterns = [
    path('search/', views.SearchResultsView.as_view(), name='post_search'),
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='post_delete'),
    path('drafts/',views.DraftListView.as_view(),name='draft_list'),
    path('published/',views.PublihedListView.as_view(),name='published_list'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),
]

web_hiring/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from crewing.settings import (TITLE_CHOICES, FLEET_CHOICES,
                                VESSEL_CHOICES, ENGLISH_CHOICES)
import datetime

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey('auth.User', null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    fleet = models.CharField(max_length=200, choices=FLEET_CHOICES)
    vessel = models.CharField(max_length=200, choices=VESSEL_CHOICES)
    salary = models.CharField(max_length=200)
    text = models.TextField(blank=True, null=True)
    joining_date = models.DateField(blank=False)
    voyage_duration = models.CharField(blank=True, null=True, max_length=200)
    sailing_area = models.CharField(blank=True, null=True, max_length=200)
    dwt = models.CharField(max_length=200, blank=True, null=True)
    years_constructed = models.PositiveIntegerField(blank=True, null=True)
    crew = models.CharField(blank=True, null=True, max_length=200)
    crewer = models.CharField(blank=True, null=True, max_length=200)
    contact = models.CharField(blank=True, null=True, max_length=200)
    email = models.CharField(blank=True, null=True, max_length=200)
    english = models.CharField(max_length=200, choices=ENGLISH_CHOICES)
    link = models.CharField(blank=True, null=True, max_length=200)
    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)


    def publish(self):
        self.publish_date = timezone.now()
        self.save()


    def get_absolute_url(self):
        return reverse('web_hiring:post_detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.title


    def __unicode__(self):
        return self.title

web_hiring/forms.py
from django import forms
from django.forms import formset_factory
from web_hiring.models import Post
from crewing.settings import (TITLE_CHOICES, FLEET_CHOICES,
                                VESSEL_CHOICES, ENGLISH_CHOICES)

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title','fleet','vessel','salary','joining_date','english',
                'crewer','contact','voyage_duration','sailing_area','dwt',
                'years_constructed','crew','text')

        labels = {
            "title":"Должность",
            "fleet":"Флот",
            "vessel":"Тип судна",
            "salary":"Зарплата($)",
            "joining_date":"Дата посадки",
            "crewer":"Крюинг",
            "contact":"Контактная информация",
            "voyage_duration":"Длительность рейса",
            "sailing_area":"Регион работы",
            "dwt":"DWT",
            "years_constructed":"Год постройки судна",
            "crew":"Экипаж",
            "english":"Уровень английского",
            "text":"Дополнительная информация"
        }

        widgets = {
            'title':forms.Select(choices=TITLE_CHOICES,attrs={'class': 'form-control'}),
            'fleet':forms.Select(choices=FLEET_CHOICES,attrs={'class': 'form-control'}),
            'vessel':forms.Select(choices=VESSEL_CHOICES,attrs={'class': 'form-control'}),
            'english':forms.Select(choices=ENGLISH_CHOICES,attrs={'class': 'form-control'}),
            'voyage_duration':forms.TextInput(attrs={'placeholder':'Длительность рейса (не обязательно)'}),
            'sailing_area':forms.TextInput(attrs={'placeholder':'Регион работы (не обязательно)'}),
            'dwt':forms.TextInput(attrs={'placeholder':'DWT (не обязательно)'}),
            'years_constructed':forms.TextInput(attrs={'placeholder':'Год постройки судна (не обязательно)'}),
            'crew':forms.TextInput(attrs={'placeholder':'Экипаж (не обязательно)'}),
            'salary':forms.TextInput(attrs={'placeholder':'Введите месячную зарплату ($)'}),
            'joining_date':forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Выберите дату', 'type':'date'})
        }

web_hiring/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from web_hiring.models import Post
from django.db.models import Q
from django.forms.models import model_to_dict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.urls import reverse_lazy
from web_hiring.forms import PostForm
from django.views.generic import (TemplateView, ListView,
                                    DetailView,CreateView,
                                    UpdateView,DeleteView,)
from django.conf import settings
from web_hiring.notificators import vacancy_notification
# Create your views here.


class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post
    paginate_by = 30

    def get_queryset(self):
        return Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')

class SearchResultsView(ListView):
    model = Post
    paginate_by = 30
    template_name = 'post_search.html'

    def get_queryset(self): # новый
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(text__icontains=query),
            publish_date__lte=timezone.now()).order_by('-publish_date')
        return object_list

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'web_hiring/post_detail.html'
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.salary = form.instance.salary + ' $'
        new_form = form.save(commit=False)
        if new_form.title == "Другое":
            form.instance.title = self.request.POST.get('titlespecify')
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'web_hiring/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('web_hiring:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'web_hiring/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(publish_date__isnull=True).order_by('create_date')

class PublihedListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'web_hiring/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user,publish_date__isnull=False).order_by('create_date')

##################################################################
##################################################################


@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    form = model_to_dict(Post.objects.get(pk=pk))
    vacancy_notification(form)
    post.publish()
    return redirect('web_hiring:post_detail',pk=pk)

templates/web_hiring/about.html
{% extends "web_hiring/base.html" %}
{% block content %}

<h1>About me:</h1>
<p>Thanks for checking it out!</p>

{% endblock %}

templates/web_hiring/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Crewing</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Poppins&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class='navbar navbar-expand navbar-default techfont custom-navbar navbar navbar-dark bg-dark'>
      <div class="container collapse navbar-collapse">
        <ul class="nav navbar-nav mr-auto">
          <li class="nav-item active">
            <a class='nav-brand nav-link' href="{% url 'web_hiring:post_list' %}">Crewing
              <i class="fa fa-anchor" aria-hidden="true"></i>
            </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'web_hiring:post_new' %}">Новая вакансия</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'web_hiring:published_list' %}">Опубликованные</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'web_hiring:draft_list' %}">Черновики</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти
              <i class="fa fa-sign-out" aria-hidden="true"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">{{ user }}
              <i class="fa fa-user-circle" aria-hidden="true"></i></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Войти
              <i class="fa fa-sign-in" aria-hidden="true"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>

    </nav>

    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_posts"><br>

            {% block content %}
            {% endblock %}
            <br>
          </div>

        </div>

      </div>

    </div>

  </body>
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script>
  jQuery('#id_title').on('change', () => {
    // You can also do this with document.querySelector('')
    if ($('#id_title option:selected').text() == 'Другое') {
        jQuery('.titlespecify').show();
    } else {
        jQuery('.title1specify').hide();
    }
  });
  </script>
</html>

templates/web_hiring/comment_form.html
{% extends "web_hiring/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

  <h1>New Comment</h1>
  <form class="post-form" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="save btn btn-success">Post Comment</button>
  </form>
  <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

templates/web_hiring/post_confirm_delete.html
{% extends "web_hiring/base.html" %}
{% block content %}

  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>

{% endblock %}

templates/web_hiring/post_detail.html
{% extends "web_hiring/base.html" %}
{% block content %}

  <h1 class="posttitle">{{post.title}}</h1>
  {% if post.publish_date %}
    <div class="date postdate">
      {{ post.publish_date }}
    </div>
  {% endif %}


    <b>Тип судна: </b>{{ post.vessel }}<br>
    <b>Зарплата: </b>{{ post.salary }}<br>
    <b>Дата посадки: </b>{{ post.joining_date }}<br>
    <b>Уровень английского: </b>{{ post.english }}<br>
    <b>Крюинг: </b>{{ post.crewer }}<br>
    {% if post.contact != '' %}
      <b>Контактная информация: </b>{{ post.contact }}<br>
    {% endif %}
    {% if post.voyage_duration != '' %}
      <b>Длительность рейса: </b>{{ post.voyage_duration }}<br>
    {% endif %}
    {% if post.sailing_area != '' %}
      <b>Регион работы: </b>{{ post.sailing_area }}<br>
    {% endif %}
    {% if post.dwt != '' %}
      <b>DWT: </b>{{ post.dwt }}<br>
    {% endif %}
    {% if post.years_constructed is not None %}
      <b>Год постройки судна: </b>{{ post.years_constructed }}<br>
    {% endif %}
    {% if post.crew != '' %}
      <b>Экипаж: </b>{{ post.crew }}<br>
    {% endif %}


  {% if user.is_authenticated and user == post.author %}
      <a class='btn btn-warning' href="{% url 'web_hiring:post_edit' pk=post.pk %}">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      </a>
      <a class='btn btn-danger' href="{% url 'web_hiring:post_delete' pk=post.pk %}">
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      </a>
      {% if not post.publish_date %}
        <a class="btn btn-success" href="{% url 'web_hiring:post_publish' pk=post.pk%}">Опубликовать
          <i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
        </a>
    {% endif %}
  {% endif %}
  <hr>
  {% if post.text != '' %}
    <b>Дополнительная информация: </b>{{ post.text|linebreaks }}<br>
  {% endif %}
{% endblock %}

templates/web_hiring/post_draft_list.html
{% extends "web_hiring/base.html" %}
{% block content %}

  {% for post in posts %}
    <div class="post">
      <p class="date">Created: {{post.created_date|date:'d-m-Y'}}</p>
      <h1>
        <a href="{% url 'web_hiring:post_detail' pk=post.pk%}">{{post.title}}</a>
      </h1>
      <p>{{post.text|truncatechars:200}}</p>
    </div>

  {% endfor %}

{% endblock %}

templates/web_hiring/post_form.html
{% extends "web_hiring/base.html" %}
{% block content %}
{% load crispy_forms_tags %}

  <h1>Новая вакансия</h1>
  {% load widget_tweaks %}
  <form method="post" action="{% url 'web_hiring:post_new' %}"  class="" novalidate>
    {% csrf_token %}
      {% for field in form %}
        {% if field.id_for_label == "id_title" %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
              {{ field|as_crispy_field }}
              <div class="mt-1 titlespecify" style="display:none">
                  <input class="form-control form-control-sm" type='text' name='titlespecify' placeholder="Укажите должность" />
              </div>
              {% for error in form.title.errors %}
                  <p class="help-block">{{ error }}</p>
              {% endfor %}
          </div>
        {% else %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            {{ field|as_crispy_field }}
          </div>
        {% endif %}
      {% endfor %}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
  </form>
{% endblock %}

templates/web_hiring/post_list.html
{% extends "web_hiring/base.html" %}
{% block content %}
{% load pagination_tags %}
{% load bootstrap4 %}

<div class="centerstage">
  <form action="{% url 'web_hiring:post_search' %}" method="get">
    <div class="row">
      <div class="col-6">
        <input class="form-control" name="q" type="text"placeholder="Поиск...">
      </div>
      <div class="col">
        <button type="submit" class="btn btn-primary mb-2">Поиск</button>
      </div>
  </form><br>
  <hr>
  <table width="100%">
  <col style="width:60%">
    <tr>
      <th colspan="2"><hr></th>
    </tr>
  {% for post in post_list %}
    <div class="post">
        <tr>
            <th>
              <div align=left>
              <h1>
                <a href="{% url 'web_hiring:post_detail' pk=post.pk %}">{{ post.title }}</a>
              </h1>
                <b>Опубликовано: </b>{{post.publish_date}}<br>
                <b>Дата посадки: </b>{{ post.joining_date }}
              </div>
              </th>
            <th>
              <div align=left>
              <h1>&nbsp</h1><b>Зарплата: </b>{{ post.salary }}<br>
                <b>Тип судна: </b>{{ post.vessel }}
              </div>
            </th>
        </tr>
        <tr>
          <th colspan="2"><hr></th>
        </tr>
    </div>
  {% endfor %}
</table>
</div>

<div class="centerstage">

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?{% param_replace page=page_obj.previous_page_number %}">&laquo;&nbsp</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;&nbsp</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }}&nbsp<span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?{% param_replace page=i %}">{{ i }}&nbsp</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?{% param_replace page=page_obj.next_page_number %}">&raquo;&nbsp</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;&nbsp</span></li>
    {% endif %}
  </ul>
{% endif %}

</div>
{% endblock %}

templates/web_hiring/post_search.html
{% extends "web_hiring/base.html" %}
{% load pagination_tags %}
{% block content %}

<div class="centerstage">
  <form action="{% url 'web_hiring:post_search' %}" method="get">
    <input name="q" type="text" placeholder="Поиск...">
  </form>
  <table width="100%">
  <col style="width:60%">
  {% for post in post_list %}
    <div class="post">
        <tr>
            <th>
              <div align=left>
              <h1>
                <a href="{% url 'web_hiring:post_detail' pk=post.pk %}">{{ post.title }}</a>
              </h1>
                <b>Хуй: </b>{{post.publish_date}}<br>
                <b>Дата посадки: </b>{{ post.joining_date }}
              </div>
              </th>
            <th>
              <div align=left>
              <h1>&nbsp</h1><b>Зарплата: </b>{{ post.salary }}<br>
                <b>Тип судна: </b>{{ post.vessel }}
              </div>
            </th>
        </tr>
        <tr>
          <th colspan="2"><hr></th>
        </tr>
    </div>
  {% endfor %}
</table>
</div>

<div class="centerstage">
    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?{% param_replace page=page_obj.previous_page_number %}">&laquo;&nbsp</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;&nbsp</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }}&nbsp<span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?{% param_replace page=i %}">{{ i }}&nbsp</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?{% param_replace page=page_obj.next_page_number %}">&raquo;&nbsp</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;&nbsp</span></li>
        {% endif %}
      </ul>
    {% endif %}
</div>
{% endblock %}